### ISSUE TITLE
Add "Auto Shutdown"

### ISSUE THREAD

**Issue by ralf401** [zammad/zammad-org#23]
Remove `APP_RESTART_CMD` and add `AUTO_SHUTDOWN`

**Comment by MrGeneration** [comment]
The control issue talked about "deprecated, will be removed"
If this is still avaiable in the next release version, we may want to deprecate it first to be able to refer to the new way.

**Comment by ralf401** [comment]
This part is not yet migrated. Skipping this for now and closing issue. Already changed in admin- and system-docs.
